general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: true
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: false
  npmExecuteScripts:
    runScripts:
    - "test"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"